



export const CoursesOffered = [
    {Course: "FEG 103", CourseTitle:'Basic Electricity I', Credit:2, Session: [100, 2]},
    {Course: "FEG 101", CourseTitle:'Engineering Mathematics I', Credit:3, Session: [100, 1]},
    {Course: "FEG 102", CourseTitle:'Engineering Mathematics II', Credit:2, Session: [100, 2]},
    {Course: "BUS 101", CourseTitle:'Introduction To Business', Credit:2, Session: [100, 1]},
    {Course: "GSS 101", CourseTitle:'Use Of English', Credit:1, Session: [100, 1]},
    {Course: "GSS 102", CourseTitle:'Use Of English II', Credit:1, Session: [100, 2]},
    {Course: "GSS 105", CourseTitle:'Humanity', Credit:2, Session: [100, 1]},
    {Course: "GSS 106", CourseTitle:'Social Science', Credit:2, Session: [100, 2]},
    {Course: "GSS 107", CourseTitle:'Nigeria Peoples And Culture', Credit:2, Session: [100, 1]},
    {Course: "GSS 108", CourseTitle:'Omenala Igbo', Credit:1, Session: [100, 1]},
    {Course: "GSS 109", CourseTitle:'Asusu Igbo', Credit:1, Session: [100, 2]},
    {Course: "ICH 101", CourseTitle:'Organic Chemistry I', Credit:2, Session: [100, 1]},
    {Course: "ICH 102", CourseTitle:'Organic Chemistry II', Credit:2, Session: [100, 2]},
    {Course: "ICH 111", CourseTitle:'Inorganic Chemistry I', Credit:2, Session: [100, 1]},
    {Course: "ICH 112", CourseTitle:'Inorganic Chemistry II', Credit:2, Session: [100, 2]},
    {Course: "MAT 101", CourseTitle:'General Mathematics I', Credit:3, Session: [100, 1]},
    {Course: "MAT 102", CourseTitle:'General Mathematics II', Credit:3, Session: [100, 2]},
    {Course: "PHY 101", CourseTitle:'General Physics I', Credit:3, Session: [100, 1]},
    {Course: "PHY 102", CourseTitle:'General Physics II', Credit:3, Session: [100, 2]},
    {Course: "PHY 107", CourseTitle:'General Physics Practical I', Credit:1, Session: [100, 1]},
    {Course: "PHY 108", CourseTitle:'General Physics Practical II', Credit:1, Session: [100, 2]},
    {Course: "BUS 204", CourseTitle:'Principles of Management', Credit:2, Session: [200, 2]},
    {Course: "FEG 221", CourseTitle:'Fluid Mechanics  ', Credit:2, Session: [200, 1]},
    {Course: "FEG 242", CourseTitle:'Thermodynamics', Credit:2, Session: [200, 2]},
    {Course: "FEG 211", CourseTitle:'Applied Mechanics I (Statics)', Credit:2, Session: [200, 1]},
    {Course: "FEG 212", CourseTitle:'Applied Mechanics II (Dynamics)', Credit:2, Session: [200, 2]},
    {Course: "FEG 215", CourseTitle:'Strength of Materials', Credit:3, Session: [200, 2]},
    {Course: "FEG 201", CourseTitle:'Basic Electricity I', Credit:3, Session: [200, 1]},
    {Course: "FEG 202", CourseTitle:'Basic Electricity II', Credit:3, Session: [200, 2]},
    {Course: "CSC 201", CourseTitle:'Computer Programming I', Credit:2, Session: [200, 1]},
    {Course: "CSC 202", CourseTitle:'Computer Programming II', Credit:2, Session: [200, 2]},
    {Course: "ICH 221", CourseTitle:'General Physical Chemistry', Credit:2, Session: [200, 1]},
    {Course: "MAT 201", CourseTitle:'Linear Algebra I', Credit:3, Session: [200, 1]},
    {Course: "MAT 202", CourseTitle:'Elementary Differential Equation', Credit:3, Session: [200, 2]},
    {Course: "FEG 213", CourseTitle:'Engineering Drawing I', Credit:2, Session: [200, 1]},
    {Course: "FEG 214", CourseTitle:'Engineering Drawing II', Credit:2, Session: [200, 2]},
    {Course: "FEG 280", CourseTitle:'Engineering in Society', Credit:2, Session: [200, 2]},
    {Course: "FEG 281", CourseTitle:'Workshop Practice I', Credit:2, Session: [200, 1]},
    {Course: "FEG 282", CourseTitle:'Workshop Practice II', Credit:2, Session: [200, 2]},
    {Course: "FEG 250", CourseTitle:'Principles of Materials Science', Credit:3, Session: [200, 1]},
    {Course: "ECE 321", CourseTitle:'elecommunications I', Credit:2, Session: [300, 1]},
    {Course: "FEG 303", CourseTitle:'Engineering Mathematics III', Credit:3, Session: [300, 1]},
    {Course: "ELE 311", CourseTitle:'Circuit Theory II', Credit:2, Session: [300, 1]},
    {Course: "ECE 323", CourseTitle:'Electrical Devices and Circuits', Credit:2, Session: [300, 1]},
    {Course: "ECE 333", CourseTitle:'Digital System Design', Credit:2, Session: [300, 1]},
    {Course: "ELE 341", CourseTitle:'Electromagnetic Field and Waves', Credit:3, Session: [300, 1]},
    {Course: "ECE 331", CourseTitle:'Signals and Systems', Credit:2, Session: [300, 1]},
    {Course: "ELE 343", CourseTitle:'Electromechanical Devices and Machines I', Credit:2, Session: [300, 1]},
    {Course: "ELE 353", CourseTitle:'Power Systems', Credit:3, Session: [300, 1]},
    {Course: "ECE 322", CourseTitle:'Telecommunication II', Credit:2, Session: [300, 2]},
    {Course: "ELE 312", CourseTitle:'Circuit Theory II', Credit:2, Session: [300, 2]},
    {Course: "ECE 328", CourseTitle:'Electronic Devices and Circuits', Credit:2, Session: [300, 2]},
    {Course: "ECE 326", CourseTitle:'Physical Electronics', Credit:2, Session: [300, 2]},
    {Course: "ECE 334", CourseTitle:'Digital System Design II', Credit:2, Session: [300, 2]},
    {Course: "ELE 382", CourseTitle:'Feedback and Control Systems', Credit:2, Session: [300, 2]},
    {Course: "ELE 372", CourseTitle:'Instrumentation And Measurement I', Credit:3, Session: [300, 2]},
    {Course: "ELE 342", CourseTitle:'Electrodynamic', Credit:3, Session: [300, 2]},
    {Course: "ELE 344", CourseTitle:'Electromechanical Devices and Machines', Credit:2, Session: [300, 2]},
    {Course: "ELE 314", CourseTitle:'Electrical Services Design', Credit:2, Session: [300, 2]},
    {Course: "ELE 403", CourseTitle:'Circuit Theory III', Credit:3, Session: [400, 1]},
    {Course: "ELE 445", CourseTitle:'Dynamics of Electrical Machine', Credit:3, Session: [400, 1]},
    {Course: "ELE 453", CourseTitle:'Alternative Energy Studies', Credit:3, Session: [400, 1]},
    {Course: "CVE 423", CourseTitle:'Engineering Contracts and Specification', Credit:2, Session: [400, 1]},
    {Course: "ELE 473", CourseTitle:'Instrumentation and Measurement II', Credit:3, Session: [400, 1]},
    {Course: "ECE 427", CourseTitle:'Advanced Circuit Techniques', Credit:2, Session: [400, 1]},
    {Course: "FEG 404", CourseTitle:'Engineering Mathematics IV', Credit:3, Session: [400, 1]},
    {Course: "ECE 505", CourseTitle:'Computer Aided Circuit Design', Credit:3, Session: [500, 1]},
    {Course: "ELE 549", CourseTitle:'Design of electromechanical Devices and Electrical Machines', Credit:3, Session: [500, 1]},
    {Course: "ELE 547", CourseTitle:'Power Electronics and Drives', Credit:3, Session: [500, 1]},
    {Course: "ELE 553", CourseTitle:'Power System Analysis', Credit:3, Session: [500, 1]},
    {Course: "ELE 557", CourseTitle:'Electric Power Transmission', Credit:3, Session: [500, 1]},
    {Course: "ECE 517", CourseTitle:'Real Time Computing and Control', Credit:3, Session: [500, 1]},
    {Course: "ELE 554", CourseTitle:'Power System Planning and Control', Credit:3, Session: [500, 2]},
    {Course: "ELE 556", CourseTitle:'Power Plant Protection and Control', Credit:3, Session: [500, 2]},
    {Course: "ELE 558", CourseTitle:'High Voltage Engineering', Credit:3, Session: [500, 2]},
    {Course: "ELE 574", CourseTitle:'Control Systems', Credit:3, Session: [500, 2]},
    {Course: "ECE 504", CourseTitle:'Network Analysis and Synthesis', Credit:3, Session: [500, 2]},
    ]